'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SynchTwinRcEngine_Interface.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _005_Task_32x42_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_005_Task_32x42_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _010_LowPriority_32x42_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_010_LowPriority_32x42_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _112_DownArrowLong_Green_32x32_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_112_DownArrowLong_Green_32x32_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property BiMoteur() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("BiMoteur", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Abort Changes.
        '''</summary>
        Friend ReadOnly Property buttonAbortChanges_EN() As String
            Get
                Return ResourceManager.GetString("buttonAbortChanges_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler Modifications.
        '''</summary>
        Friend ReadOnly Property buttonAbortChanges_FR() As String
            Get
                Return ResourceManager.GetString("buttonAbortChanges_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Center.
        '''</summary>
        Friend ReadOnly Property buttonAuxCenter_EN() As String
            Get
                Return ResourceManager.GetString("buttonAuxCenter_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Milieu.
        '''</summary>
        Friend ReadOnly Property buttonAuxCenter_FR() As String
            Get
                Return ResourceManager.GetString("buttonAuxCenter_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Settings &gt;&gt;.
        '''</summary>
        Friend ReadOnly Property buttonConfig_EN() As String
            Get
                Return ResourceManager.GetString("buttonConfig_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration &gt;&gt;.
        '''</summary>
        Friend ReadOnly Property buttonConfig_FR() As String
            Get
                Return ResourceManager.GetString("buttonConfig_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connection.
        '''</summary>
        Friend ReadOnly Property buttonConnect_EN() As String
            Get
                Return ResourceManager.GetString("buttonConnect_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connexion.
        '''</summary>
        Friend ReadOnly Property buttonConnect_FR() As String
            Get
                Return ResourceManager.GetString("buttonConnect_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Send.
        '''</summary>
        Friend ReadOnly Property buttonDebugSend_EN() As String
            Get
                Return ResourceManager.GetString("buttonDebugSend_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Envoi.
        '''</summary>
        Friend ReadOnly Property buttonDebugSend_FR() As String
            Get
                Return ResourceManager.GetString("buttonDebugSend_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Glows On/Off.
        '''</summary>
        Friend ReadOnly Property buttonGlowOnOff_EN() As String
            Get
                Return ResourceManager.GetString("buttonGlowOnOff_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bougies On/Off.
        '''</summary>
        Friend ReadOnly Property buttonGlowOnOff_FR() As String
            Get
                Return ResourceManager.GetString("buttonGlowOnOff_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Master.
        '''</summary>
        Friend ReadOnly Property buttonModuleType_EN() As String
            Get
                Return ResourceManager.GetString("buttonModuleType_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Maître.
        '''</summary>
        Friend ReadOnly Property buttonModuleType_FR() As String
            Get
                Return ResourceManager.GetString("buttonModuleType_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Motor.
        '''</summary>
        Friend ReadOnly Property buttonMotors_EN() As String
            Get
                Return ResourceManager.GetString("buttonMotors_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moteur.
        '''</summary>
        Friend ReadOnly Property buttonMotors_FR() As String
            Get
                Return ResourceManager.GetString("buttonMotors_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exit.
        '''</summary>
        Friend ReadOnly Property buttonQuit_EN() As String
            Get
                Return ResourceManager.GetString("buttonQuit_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Quitter.
        '''</summary>
        Friend ReadOnly Property buttonQuit_FR() As String
            Get
                Return ResourceManager.GetString("buttonQuit_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Read.
        '''</summary>
        Friend ReadOnly Property buttonRead_EN() As String
            Get
                Return ResourceManager.GetString("buttonRead_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Lire.
        '''</summary>
        Friend ReadOnly Property buttonRead_FR() As String
            Get
                Return ResourceManager.GetString("buttonRead_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reset Settings.
        '''</summary>
        Friend ReadOnly Property buttonResetSettings_EN() As String
            Get
                Return ResourceManager.GetString("buttonResetSettings_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à RAZ Configuration.
        '''</summary>
        Friend ReadOnly Property buttonResetSettings_FR() As String
            Get
                Return ResourceManager.GetString("buttonResetSettings_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Backup.
        '''</summary>
        Friend ReadOnly Property buttonSaveComPort_EN() As String
            Get
                Return ResourceManager.GetString("buttonSaveComPort_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauvegarde.
        '''</summary>
        Friend ReadOnly Property buttonSaveComPort_FR() As String
            Get
                Return ResourceManager.GetString("buttonSaveComPort_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Save Settings.
        '''</summary>
        Friend ReadOnly Property buttonSaveSettings_EN() As String
            Get
                Return ResourceManager.GetString("buttonSaveSettings_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sauver Configuration.
        '''</summary>
        Friend ReadOnly Property buttonSaveSettings_FR() As String
            Get
                Return ResourceManager.GetString("buttonSaveSettings_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Confirm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Confirm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GlowPlug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GlowPlug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Serial Port.
        '''</summary>
        Friend ReadOnly Property groupBoxComPort_EN() As String
            Get
                Return ResourceManager.GetString("groupBoxComPort_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Port Série.
        '''</summary>
        Friend ReadOnly Property groupBoxComPort_FR() As String
            Get
                Return ResourceManager.GetString("groupBoxComPort_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Settings.
        '''</summary>
        Friend ReadOnly Property groupBoxSettings_EN() As String
            Get
                Return ResourceManager.GetString("groupBoxSettings_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Configuration.
        '''</summary>
        Friend ReadOnly Property groupBoxSettings_FR() As String
            Get
                Return ResourceManager.GetString("groupBoxSettings_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joystick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joystick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Auxiliary:.
        '''</summary>
        Friend ReadOnly Property labelAuxiPosition_EN() As String
            Get
                Return ResourceManager.GetString("labelAuxiPosition_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Auxiliaire:.
        '''</summary>
        Friend ReadOnly Property labelAuxiPosition_FR() As String
            Get
                Return ResourceManager.GetString("labelAuxiPosition_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Channel Auxiliary Simulation.
        '''</summary>
        Friend ReadOnly Property labelAuxiRudderSimu_EN() As String
            Get
                Return ResourceManager.GetString("labelAuxiRudderSimu_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Canal Auxiliaire Simulation.
        '''</summary>
        Friend ReadOnly Property labelAuxiRudderSimu_FR() As String
            Get
                Return ResourceManager.GetString("labelAuxiRudderSimu_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Center Servo1:.
        '''</summary>
        Friend ReadOnly Property labelCenterServo1_EN() As String
            Get
                Return ResourceManager.GetString("labelCenterServo1_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Centre Servo1:.
        '''</summary>
        Friend ReadOnly Property labelCenterServo1_FR() As String
            Get
                Return ResourceManager.GetString("labelCenterServo1_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Center Servo2:.
        '''</summary>
        Friend ReadOnly Property labelCenterServo2_EN() As String
            Get
                Return ResourceManager.GetString("labelCenterServo2_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Centre Servo2:.
        '''</summary>
        Friend ReadOnly Property labelCenterServo2_FR() As String
            Get
                Return ResourceManager.GetString("labelCenterServo2_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Module configuration editor:.
        '''</summary>
        Friend ReadOnly Property labelConfigModule_EN() As String
            Get
                Return ResourceManager.GetString("labelConfigModule_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Editeur de la configuration du module:.
        '''</summary>
        Friend ReadOnly Property labelConfigModule_FR() As String
            Get
                Return ResourceManager.GetString("labelConfigModule_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Generale Maxi:.
        '''</summary>
        Friend ReadOnly Property labelGeneralePositionMaxi_EN() As String
            Get
                Return ResourceManager.GetString("labelGeneralePositionMaxi_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Maxi Générale:.
        '''</summary>
        Friend ReadOnly Property labelGeneralePositionMaxi_FR() As String
            Get
                Return ResourceManager.GetString("labelGeneralePositionMaxi_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Generale Mini:.
        '''</summary>
        Friend ReadOnly Property labelGeneralePositionMini_EN() As String
            Get
                Return ResourceManager.GetString("labelGeneralePositionMini_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Mini Générale:.
        '''</summary>
        Friend ReadOnly Property labelGeneralePositionMini_FR() As String
            Get
                Return ResourceManager.GetString("labelGeneralePositionMini_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Idle Servo 1:.
        '''</summary>
        Friend ReadOnly Property labelIdleServo1_EN() As String
            Get
                Return ResourceManager.GetString("labelIdleServo1_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Ralenti Servo 1:.
        '''</summary>
        Friend ReadOnly Property labelIdleServo1_FR() As String
            Get
                Return ResourceManager.GetString("labelIdleServo1_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Idle Servo 2:.
        '''</summary>
        Friend ReadOnly Property labelIdleServo2_EN() As String
            Get
                Return ResourceManager.GetString("labelIdleServo2_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Position Ralenti Servo 2:.
        '''</summary>
        Friend ReadOnly Property labelIdleServo2_FR() As String
            Get
                Return ResourceManager.GetString("labelIdleServo2_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Internal Voltage:.
        '''</summary>
        Friend ReadOnly Property labelIntVoltage_EN() As String
            Get
                Return ResourceManager.GetString("labelIntVoltage_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voltage Interne:.
        '''</summary>
        Friend ReadOnly Property labelIntVoltage_FR() As String
            Get
                Return ResourceManager.GetString("labelIntVoltage_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Radio Mode:.
        '''</summary>
        Friend ReadOnly Property labelMode_EN() As String
            Get
                Return ResourceManager.GetString("labelMode_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode Radio:.
        '''</summary>
        Friend ReadOnly Property labelMode_FR() As String
            Get
                Return ResourceManager.GetString("labelMode_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Channel Motors Simulation.
        '''</summary>
        Friend ReadOnly Property labelMotorsSimu_EN() As String
            Get
                Return ResourceManager.GetString("labelMotorsSimu_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Canal Moteurs Simulation.
        '''</summary>
        Friend ReadOnly Property labelMotorsSimu_FR() As String
            Get
                Return ResourceManager.GetString("labelMotorsSimu_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Number of Blades or Magnets:.
        '''</summary>
        Friend ReadOnly Property labelNbrBlades_EN() As String
            Get
                Return ResourceManager.GetString("labelNbrBlades_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nombre de pales ou d&apos;aimants:.
        '''</summary>
        Friend ReadOnly Property labelNbrBlades_FR() As String
            Get
                Return ResourceManager.GetString("labelNbrBlades_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Radio Mode:.
        '''</summary>
        Friend ReadOnly Property labelRadioMode_EN() As String
            Get
                Return ResourceManager.GetString("labelRadioMode_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mode Radio:.
        '''</summary>
        Friend ReadOnly Property labelRadioMode_FR() As String
            Get
                Return ResourceManager.GetString("labelRadioMode_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reverse Aux:.
        '''</summary>
        Friend ReadOnly Property labelReverseAuxi_EN() As String
            Get
                Return ResourceManager.GetString("labelReverseAuxi_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Inversion Aux:.
        '''</summary>
        Friend ReadOnly Property labelReverseAuxi_FR() As String
            Get
                Return ResourceManager.GetString("labelReverseAuxi_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reverse Servo1:.
        '''</summary>
        Friend ReadOnly Property labelReverseServo1_EN() As String
            Get
                Return ResourceManager.GetString("labelReverseServo1_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Inversion Servo1:.
        '''</summary>
        Friend ReadOnly Property labelReverseServo1_FR() As String
            Get
                Return ResourceManager.GetString("labelReverseServo1_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reverse Servo2:.
        '''</summary>
        Friend ReadOnly Property labelReverseServo2_EN() As String
            Get
                Return ResourceManager.GetString("labelReverseServo2_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Inversion Servo2:.
        '''</summary>
        Friend ReadOnly Property labelReverseServo2_FR() As String
            Get
                Return ResourceManager.GetString("labelReverseServo2_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Speed Module Answer:.
        '''</summary>
        Friend ReadOnly Property labelSpeedModuleAnswer_EN() As String
            Get
                Return ResourceManager.GetString("labelSpeedModuleAnswer_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse Réponse Module:.
        '''</summary>
        Friend ReadOnly Property labelSpeedModuleAnswer_FR() As String
            Get
                Return ResourceManager.GetString("labelSpeedModuleAnswer_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Speed Motors Mini/Maxi (rpm):.
        '''</summary>
        Friend ReadOnly Property labelSpeedMotorMinMaxRPM_EN() As String
            Get
                Return ResourceManager.GetString("labelSpeedMotorMinMaxRPM_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vitesse Moteurs Mini/Maxi (tr/mn):.
        '''</summary>
        Friend ReadOnly Property labelSpeedMotorMinMaxRPM_FR() As String
            Get
                Return ResourceManager.GetString("labelSpeedMotorMinMaxRPM_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Start Synchro Servos:.
        '''</summary>
        Friend ReadOnly Property labelStartSynchroMotors_EN() As String
            Get
                Return ResourceManager.GetString("labelStartSynchroMotors_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Début Synchro Servos:.
        '''</summary>
        Friend ReadOnly Property labelStartSynchroMotors_FR() As String
            Get
                Return ResourceManager.GetString("labelStartSynchroMotors_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Terminal is ready !.
        '''</summary>
        Friend ReadOnly Property labelTerminalWelcome_EN() As String
            Get
                Return ResourceManager.GetString("labelTerminalWelcome_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Terminal prêt !.
        '''</summary>
        Friend ReadOnly Property labelTerminalWelcome_FR() As String
            Get
                Return ResourceManager.GetString("labelTerminalWelcome_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_arduino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_arduino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property logo_arduino1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_arduino1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mode1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mode1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property monitor() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mosquito() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mosquito", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mosquito_dessus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mosquito_dessus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotAllowed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotAllowed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à English.
        '''</summary>
        Friend ReadOnly Property optLangEN_EN() As String
            Get
                Return ResourceManager.GetString("optLangEN_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Anglais.
        '''</summary>
        Friend ReadOnly Property optLangEN_FR() As String
            Get
                Return ResourceManager.GetString("optLangEN_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à French.
        '''</summary>
        Friend ReadOnly Property optLangFR_EN() As String
            Get
                Return ResourceManager.GetString("optLangFR_EN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Français.
        '''</summary>
        Friend ReadOnly Property optLangFR_FR() As String
            Get
                Return ResourceManager.GetString("optLangFR_FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rectangle_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rectangle_gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rectangle_rouge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rectangle_rouge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rectangle_vert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rectangle_vert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Servo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Servo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrackBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrackBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnderConstruction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnderConstruction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
