= Librairie Asynchrone pour Arduino =

Introduction

Sur les différents forums de discussion "Arduino", on lit souvent:
"Je fais clignotter une LED toutes les 5 secondes avec la fonction delay() et 
je mesure la largeur d'une impulsion provenant d'un récepteur RC avec pulseIn(), 
puis après traitement, je pilote un servo à l'aide de la librairie <SoftwareServo>. 
Mon servo fait n'importe quoi. Je constate que je rate beaucoup d'impulsions et 
que mon servo ne reçoit pas d'impulsion pendant le délai de 5 secondes:  il est "mou". 
Comment puis-je faire ces 3 actions en même temps."
Voilà typiquement, un cas programmation dit "synchrone": la fonction delay() de 5 secondes 
est une fonction bloquante, le micro-contrôleur ne fait (quasi) rien d'autre que d'attendre 
que les 5 secondes se soient écoulées.

Pour pulseIn(), c'est la même chose, si aucune impulsion, n'arrive, par défaut, 
cette fonction ne rend pas la main avant une seconde:  il s'agit d'une fonction quasi bloquante. 
A l'échelle des capacités de traitement des micro-contrôleurs, une seconde, c'est une éternité!
L'asynchrone: une solution élégante, efficace et abordable

L'auteur de ces lignes propose donc une solution: la programmation en mode dit "asynchrone" à l'aide 
d'une collection de  librairies non bloquantes taillées pour les applications orientées "Radio-Commande". 
Pour les évènements entrants  (ex: lecture impulsion) Asynchrone signifie qu'il n'est pas nécessaire 
d'attendre qu'une action soit finie avant de rendre la main au micro-contrôleur. Le simple test d'un 
indicateur via une fonction de la librairie suffit à savoir si l'action est terminée ou pas. 
Pour les évènements sortants (ex: génération d'une impulsion), Asynchrone signifie qu'ils sont 
exécutés dans la boucle principale, dès que le moment est arrivé, ou bien en interruption timer.
